### ISSUE TITLE
Issues with "ValueError: invalid literal for int() with base 10" error

### ISSUE THREAD

**Issue by jstrat31** [yeahjack/chatgpt_zulip_bot#5]
Hello, 
I'm getting the following errors when I attempt to execute the bot script. 

Traceback (most recent call last):
  File "C:\Temp\zulipbot\chatgpt_zulip_bot\chatgpt_zulip_bot.py", line 13, in <module>
    USER_ID = int(config["settings"]["USER_ID"])
ValueError: invalid literal for int() with base 10: "'hartley'"

**Comment by jstrat31** [comment]
That was my bad. I found the numbers for user ID and such in zulip as soon as I submitted this issue. 
But now I'm running into this issue. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Temp\zulipbot\chatgpt_zulip_bot\chatgpt_zulip_bot.py", line 77, in <module>
    bot = ChatGPTZulipBot(ZULIP_CONFIG)
  File "C:\Temp\zulipbot\chatgpt_zulip_bot\chatgpt_zulip_bot.py", line 19, in __init__
    super().__init__(config_file=config_file)
  File "C:\Users\jhartley.LMLAWFIRM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zulip\__init__.py", line 518, in __init__
    server_settings = self.get_server_settings()
  File "C:\Users\jhartley.LMLAWFIRM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zulip\__init__.py", line 1137, in get_server_settings
    return self.call_endpoint(
  File "C:\Users\jhartley.LMLAWFIRM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zulip\__init__.py", line 735, in call_endpoint
    return self.do_api_query(
  File "C:\Users\jhartley.LMLAWFIRM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\zulip\__init__.py", line 677, in do_api_query
    raise UnrecoverableNetworkError("SSL Error")
zulip.UnrecoverableNetworkError: SSL Error

**Comment by yeahjack** [comment]
Hello,

I am glad that your first question gets resolved. Yes, the ID should be an integer. Maybe I will give an introduction in the `README.md`.

For your second question, may I assume that you are using proxies to access the OpenAI API? If so, that could be the reason since I am deploying this program on a server where the API access is not restricted. I might add the proxy configuration part in the `config.ini` file.

Thank you very much!

**Comment by jstrat31** [comment]
I'm not using any proxies, but we do have very strict firewall rules. Does the errors above point to not being able to communicate with the OpenAI API's? I was worried it might be due to use using a custom SSL cert for Zuilp for our local domain. Also Zulip has no inbound internet access. We only connect to it while inside our network.

**Comment by yeahjack** [comment]
I am afraid the custom SSL cert might be the reason for the OpenAI API. 
I didn't have any experience in this kind of demand. I searched the Internet and found that the library `certifi` might work. Not sure about this.
If it didn't, maybe you need to subclass the OpenAI API to override the process of requesting network requests.

**Comment by yeahjack** [comment]
Found an inquiry in the OpenAI community, might help. https://community.openai.com/t/how-can-i-disable-ssl-verification-when-using-openai-api-in-python/110837/4

**Comment by yeahjack** [comment]
Hello,

Since I got no further replies, I will close this issue.

If you have any other issues, please feel free to ask.
